name: CI/CD Pipeline - Back Ventas

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: ./Springboot-API-REST
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/back-ventas:latest

      - name: Despliegue en EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_PROXY: ${{ secrets.EC2_PROXY_HOST }}
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "$SSH_KEY" | tr -d '\r' > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          H=$(printf '%s' "$EC2_HOST"  | tr -d '\r\n ')
          U=$(printf '%s' "$EC2_USER"  | tr -d '\r\n ')
          P=$(printf '%s' "$EC2_PROXY" | tr -d '\r\n ')
          [ -z "$H" ] && echo "ERROR: EC2_HOST vacio" && exit 1
          [ -z "$P" ] && echo "ERROR: EC2_PROXY vacio" && exit 1
          [ -z "$U" ] && echo "ERROR: EC2_USER vacio" && exit 1
          echo "KEY bytes: $(wc -c < /tmp/ssh_key)"
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -J ${U}@${P} ${U}@${H} "docker pull ${DOCKER_USER}/back-ventas:latest || true; docker stop back-ventas || true; docker rm back-ventas || true; docker run -d --name back-ventas -p 8080:8080 -e DB_ENDPOINT=${DB_ENDPOINT} -e DB_PORT=3306 -e DB_NAME=ventas_db -e DB_USERNAME=${DB_USERNAME} -e DB_PASSWORD=${DB_PASSWORD} ${DOCKER_USER}/back-ventas:latest"
